### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by magical** [OSU-CS492-W19/final-project-team-pikachu#11]
**features:**
- [x] pokemon list
- [x] team list
- [x] click on team member for more details - FAB branch
- [x] adding to team
- [ ] type analysis pane 
    - [x] defensive
    - [ ] offensive
- [x] multiple teams?

**polish**:
- [x] show actual names instead of identifiers</strike>
- [x] searching/filtering within the pokemon list

**plumbing**
- [x] team persistence (sqlite)
- [x] add repository for the viewmodel to pull from
- [x] grab json from github instead of pokeapi to work around api limits?

**other**
- [x] Move code to folders (utils, etc.)
- [x] Signup for a demo time (code is due before the demo time). https://calendar.google.com/calendar/selfsched?sstoken=UUdVZU15RFNoakRJfGRlZmF1bHR8ZmUxNjU2MDI5MTY2YjdiY2YyNzk0YjQ3OThlODc2ZDM

**Comment by mwyoung** [comment]
@hammockt (and @magical),
I sent out an email to the OSU email about when we should sign up for a demo time. When do you both want to do it?
